"""quiz"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "12f47498aa5f"
down_revision = "7b2f2b8a0c31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_quizzes",
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column(
            "generation_mode",
            sa.Enum("document", "query", name="quiz_generation_mode"),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source_payload", sa.JSON(), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("source_document_version", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id",
            "source_document_version",
            "generation_mode",
            name="uq_document_quizzes_document_version_mode",
        ),
    )
    op.create_index(
        op.f("ix_document_quizzes_document_id"),
        "document_quizzes",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_quizzes_generation_mode"),
        "document_quizzes",
        ["generation_mode"],
        unique=False,
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["document_quizzes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quiz_attempts_document_id"),
        "quiz_attempts",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quiz_attempts_quiz_id"), "quiz_attempts", ["quiz_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_attempts_quiz_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_document_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    op.drop_index(
        op.f("ix_document_quizzes_generation_mode"), table_name="document_quizzes"
    )
    op.drop_index(
        op.f("ix_document_quizzes_document_id"), table_name="document_quizzes"
    )
    op.drop_table("document_quizzes")
    # ### end Alembic commands ###
